```{r}
#Importando las librerias
library(haven)
library(rpart)
library(rpart.plot)
library(dplyr)
library(tidyverse)
library(mltools)
library(data.table)
library(ggplot2)
library(forcats)

```

```{r}
str(data_total)
```

```{r}
#Importando los archivos .sav

a_2018 <- read_sav("2018.sav")
a_2019 <- read_sav("2019.sav")
a_2020 <- read_sav("2020.sav")
a_2021 <- read_sav("2021.sav")
a_2022 <- read_sav("2022.sav")

# Unir los data frames usando rbind
data_total <- rbind(a_2018, a_2019, a_2020, a_2021, a_2022)

# Ver el resultado
print(data_total)
```
```{r}
data_total$CAUFIN <- as.factor(data_total$CAUFIN)
data_total$SEXO  <- as.factor(data_total$SEXO)
data_total$TRATARECIB   <- as.factor(data_total$TRATARECIB)
# Ver el tipo de la columna 'CAUFIN'
str(data_total$CAUFIN)

```
convirtiendo a factores

```{r}
data_total <- data_total %>% 
  mutate(across(where(~ !is.logical(.) & !is.factor(.)), as.factor))


```


#Arbol No. 1 

```{r}
#este

#library(rpart)
#library(rpart.plot)

data_total$CAUFIN_numeric <- as.numeric(factor(data_total$CAUFIN))

enf_pert <- rpart(PPERTENENCIA ~
                DIASESTANCIA+
                 CAUFIN_numeric+
                 EDAD,
               data = data_total, method = "class",control = rpart.control(minsplit = 20, cp = 0.01, maxdepth = 5))

# Podar el árbol
#enf_pert_podado <- prune(enf_pert, cp = 0.01)

# Visualizar el árbol podado
#rpart.plot(enf_pert_podado, type = 2, extra = 0, under = TRUE, fallen.leaves = TRUE, 
           #box.palette = "BuGn", main = "Pertenencia según enfermedades", cex = 0.45)


rpart.plot(enf_pert, type=2, extra=0, under = TRUE, fallen.leaves = TRUE, box.palette = "BuGn", 
           main ="Pertenencia según enfermedades", cex = 0.45)

pertenencia <- data.frame(
  DIASESTANCIA=c(3),
  CAUFIN_numeric = c(43),
  EDAD=c(40))

result_pert <- predict(enf_pert,pertenencia, type="class")
result_pert

```



```{r}

library(rpart)
library(rpart.plot)

# Limpieza y preparación de datos
# Eliminar valores NA
a_2018 <- na.omit(a_2018)

# Convertir variables a los tipos de datos correctos
a_2018$CAUFIN <- as.factor(a_2018$CAUFIN)


enf_pert <- rpart(PPERTENENCIA ~
                 DIASESTANCIA +
                 #CAUFIN + 
                 EDAD,
               data = a_2018, method = "class",control = rpart.control(cp = 0.01))


rpart.plot(enf_pert, type=2, under = TRUE, fallen.leaves = TRUE, box.palette = "BuGn", 
           main ="Pertenencia según enfermedades", cex = 0.45)

pertenencia <- data.frame(
  DIASESTANCIA = c(3),
 #CAUFIN = factor("A06",levels = levels(a_2018$CAUFIN)),
  EDAD = c(25))

result_pert <- predict(enf_pert,pertenencia, type="class")
result_pert
```

#Arbol No. 2

```{r}
library(rpart)
library(rpart.plot)

data_total <- na.omit(data_total)
data_total$CAUFIN <- as.factor(data_total$CAUFIN)

motivo_enfermedad <- rpart(CAUFIN ~
                SEXO+
                DEPTORESIDEN+
                DIASESTANCIA,
               data = data_total, method = "class",control = rpart.control(minsplit = 10, cp = 0.01, maxdepth = 15))


rpart.plot(motivo_enfermedad, type=2, extra=0, under = TRUE, fallen.leaves = TRUE, box.palette = "BuGn", 
           main ="Motivo de enfermedad según lugar de residencia", cex = 0.50)

motivo <- data.frame(
  SEXO = c(2),
  DEPTORESIDEN = c(9),
  DIASESTANCIA = c(3))

result_motivo <- predict(motivo_enfermedad,motivo, type="class")
result_motivo

```
```{r}
#arbol2.2

library(rpart)
library(rpart.plot)

data_total <- na.omit(data_total)
data_total$CAUFIN <- as.factor(data_total$CAUFIN)
#levels(data_total$CAUFIN) <- droplevels(data_total$CAUFIN)

motivo_enfermedad <- rpart(CAUFIN ~
                SEXO+
                DEPTORESIDEN+
                DIASESTANCIA,
               data = data_total, method = "class",control = rpart.control(minsplit = 15, maxdepth = 15))

rpart.plot(motivo_enfermedad, type=2, under = TRUE, box.palette = "BuGn",main ="Motivo de enfermedad según lugar de residencia", cex = 0.50)

motivo <- data.frame(
  SEXO = c(2),
  DEPTORESIDEN = c(9),
  DIASESTANCIA = c(3))

result_motivo <- predict(motivo_enfermedad,motivo, type="class")
result_motivo

```


#Arbol No. 3
Enfermedades que padecen segun el genero  
```{r}

library(rpart)
library(rpart.plot)

a_2019 <- na.omit(a_2019)
a_2019$CAUFIN <- as.factor(a_2019$CAUFIN)
levels(a_2019$CAUFIN) <- droplevels(a_2019$CAUFIN)

sexo_padece <- rpart(SEXO ~
                EDAD+
                DEPTORESIDEN+
                CAUFIN,
               data = a_2019, method = "class")


rpart.plot(sexo_padece, type=2, extra=0, under = TRUE, fallen.leaves = TRUE, box.palette = "BuGn", 
           main ="Padecimiento segun el sexo y la edad del paciente", cex = 0.50)

padece <- data.frame(
  EDAD = c(24),
  DEPTORESIDEN = c(1))
 CAUFIN = factor("A06",levels = levels(a_2019$CAUFIN))

result_padece <- predict(sexo_padece,padece, type="class")
result_padece
```

#Arbol No. 4

```{r}
#data_total <- na.omit(data_total)
#data_total$CAUFIN <- as.factor(data_total$CAUFIN)
#data_total<- droplevels(data_total$CAUFIN)

egreso_sexo <- rpart(CONDIEGRES ~
                SEXO+
                CAUFIN+
                TRATARECIB+
                DIASESTANCIA,
               data = data_total, method = "class")


rpart.plot(egreso_sexo, type=2, extra=0, under = TRUE, box.palette = "BuGn", 
           main ="Condicion de egreso segun sexo y tratamiento recibido", cex = 0.50)

eg_s <- data.frame(
  SEXO = c(1),
  CAUFIN = factor("A06", levels = levels(data_total$CAUFIN)),
  TRATARECIB = c(2),
  DIASESTANCIA = c(4))

result_egs <- predict(egreso_sexo,eg_s, type="class")
result_egs
```

```{r}
# Asignar un número único a cada valor de CAUFIN

data_total$CAUFIN_numeric <- as.numeric(factor(data_total$CAUFIN))
mes_enf <- rpart(SEXO ~
                EDAD+
                DIASESTANCIA+
                CAUFIN_numeric,
               data = data_total, method = "class")


rpart.plot(mes_enf, type=2, extra=0, under = TRUE, box.palette = "BuGn", 
           main ="Género de constancia de enfermedad", cex = 0.50)

mes_g <- data.frame( 
  EDAD = c(25),
  DIASESTANCIA = c(4),
  CAUFIN_numeric = c(9))
 
  
pred <- predict(mes_enf,mes_g, type="class")
pred

```

```{r}
#data_total <- na.omit(data_total)
#data_total$CAUFIN <- as.factor(data_total$CAUFIN)
#data_total<- droplevels(data_total$CAUFIN)

data_total$CAUFIN_numeric <- as.numeric(factor(data_total$CAUFIN))
egreso_sexo <- rpart(CONDIEGRES ~
                SEXO+
                CAUFIN_numeric+
                DIASESTANCIA,
               data = data_total, method = "class")


rpart.plot(egreso_sexo, type=2, extra=0, under = TRUE, box.palette = "BuGn", 
           main ="Condicion de egreso segun sexo y tratamiento recibido", cex = 0.50)

eg_s <- data.frame(
  SEXO = c(1),
  CAUFIN_numeric = c(1077),
  DIASESTANCIA = c(3))

result_egs <- predict(egreso_sexo,eg_s, type="class")
result_egs
```

